//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexSensei.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexSensei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_RunRegex {
            get {
                return ResourceManager.GetString("Button_RunRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LB_ReOptions {
            get {
                return ResourceManager.GetString("LB_ReOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Compiled {
            get {
                return ResourceManager.GetString("MenuItem_Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Culture Invariant に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_CultureInvariant {
            get {
                return ResourceManager.GetString("MenuItem_CultureInvariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECMA Script に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ECMAScript {
            get {
                return ResourceManager.GetString("MenuItem_ECMAScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explicit Capture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_ExplicitCapture {
            get {
                return ResourceManager.GetString("MenuItem_ExplicitCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_IgnoreCase {
            get {
                return ResourceManager.GetString("MenuItem_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Pattern WS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_IgnorePatternWhitespace {
            get {
                return ResourceManager.GetString("MenuItem_IgnorePatternWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiline に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Multiline {
            get {
                return ResourceManager.GetString("MenuItem_Multiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right to Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_RightToLeft {
            get {
                return ResourceManager.GetString("MenuItem_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuItem_Singleline {
            get {
                return ResourceManager.GetString("MenuItem_Singleline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex Sensei に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WT_Application {
            get {
                return ResourceManager.GetString("WT_Application", resourceCulture);
            }
        }
    }
}
